
export const CHANGE_URL_CONTENT = "CHANGE_URL_CONTENT";
export const REQUEST_URL_PENDING = "REQUEST_URL_PENDING";
export const REQUEST_URL_SUCCESS = "REQUEST_URL_SUCCESS";
export const REQUEST_URL_FAILED = "REQUEST_URL_FAILED";
