
export const getImageUrl = {
    CHANGE_URL_CONTENT: "CHANGE_URL_CONTENT",
    REQUEST_URL_PENDING: "REQUEST_URL_PENDING",
    REQUEST_URL_SUCCESS: "REQUEST_URL_SUCCESS",
    REQUEST_URL_FAILED: "REQUEST_URL_FAILED",
    GET_DIRECT_URL_CONTENT: "GET_DIRECT_URL_CONTENT",
    GET_DIRECT_URL_EMPTY: "GET_DIRECT_URL_EMPTY"
}

export const ON_ROUTER_CHANGE = "ON_ROUTER_CHANGE";



